# 현재 docker image 테스트 후 배포
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k-django
  name: k-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k-django
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k-django
    spec:
      containers:
      - image: beomzh/pmc
        imagePullSecrets: 
          - name:  myregistrykey # 생성 예정
        name: django
        ports:
        - containerPort: 8000
        resources: {}
status: {}
