apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-prepull
  labels:
    app: image-prepull
spec:
  selector:
    matchLabels:
      app: image-prepull
  template:
    metadata:
      labels:
        app: image-prepull
    spec:
      containers:
      - name: image-prepull
        image: docker:24.0.5-cli
        command: [ "sh", "-c", "while true; do echo 'Pulling image...'; docker pull beomzh/pmc ; echo 'Image pulled successfully'; sleep 3600; done" ]
        imagePullPolicy: Always
        # docker cli를 사용하기 위해
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      imagePullSecrets:
      - name: myregistrykey
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      # root 유저로 실행
      securityContext:
        runAsUser: 0
